inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - '.gems/**/*'
    - 'vendor/**/*'
  SuggestExtensions: false
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  AllowedMethods: expect

Style/Documentation:
  Exclude:
    - spec/**/*
    - features/**/*

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/Encoding:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Gemspec/RubyVersionGlobalsUsage: # maybe later
  Enabled: false
Gemspec/OrderedDependencies: # nonsense
  Enabled: false
Gemspec/RequiredRubyVersion: # rubocop errors when specifying TargetRubyVersion as 1.8.7
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Lint/AmbiguousRegexpLiteral: # not a big deal
  Enabled: false
Lint/AssignmentInCondition: # "I know I'm using an assignment as a condition. It's not a mistake."
  Enabled: false
