language: ruby

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0

cache: bundler

# NOTE: please, specify rubies versions in descending order,
# it adds convenience when checking out travis-ci builds dashboard
# also, newer rubies will be built first
jobs:
  include:
  - rvm: 2.7

  - rvm: 2.6

  - rvm: 2.5

  - rvm: jruby-9.2 # 2.5 compatible
    jdk: openjdk8

  - rvm: 2.4

  - rvm: 2.3

  - rvm: jruby-9.1 # 2.3 compatible
    jdk: openjdk8

  - rvm: 2.2

  - rvm: jruby-9.0 # 2.2 compatible
    jdk: openjdk8

  - rvm: 2.1

  - name: 'Ruby: 2.0'
    rvm: 2.0

  - rvm: 1.9
    env: CUCUMBER=false # getting to work cucumber environment is kinda pain here

  - rvm: jruby-1.7
    gemfile: gemfiles/jruby-1.7/Gemfile
    env: CUCUMBER=false # getting to work cucumber environment is kinda pain here
    jdk: openjdk8

  - rvm: 1.8
    dist: trusty
    gemfile: gemfiles/ruby-1.8/Gemfile
    env: CUCUMBER=false # getting to work cucumber environment is kinda pain here
